// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hoiewtsfcbnictenvurz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvaWV3dHNmY2JuaWN0ZW52dXJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMTc4NTAsImV4cCI6MjA2OTg5Mzg1MH0.S7zKqIJVKTFjgfYphWCSVgMP9dHdvqr9kwMwiv4PQ5w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});